#!/bin/bash
set -e

# get_script_dir
# Prints the directory that contains the currently executing script. (Follows symlinks.)
# From: https://www.ostricher.com/2014/10/the-right-way-to-get-the-directory-of-a-bash-script/
get_script_dir () {
  # BASH_SOURCE is a stack of scripts called in order. BASH_SOURCE[0] is this script,
  SOURCE="${BASH_SOURCE[0]}"
  # While $SOURCE is a symlink, resolve it
  while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$( readlink "$SOURCE" )"
    # If $SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  done
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  echo "$DIR"
}

earthly +dev

root=$(get_script_dir)
docker run -it --rm \
	--mount "type=bind,src=$root/bookmarklets,dst=/app/bookmarklets" \
	--mount "type=bind,src=$root/src,dst=/app/src" \
	-p "3000:3000" \
	-p "24678:24678" \
	my-app-dev:latest
	
