name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.5.18
      - uses: actions/checkout@v2
      - name: Pre-build check
        run: earthly --version
      - name: Build the site
        run: earthly --build-arg BASE_URL='/bookmarklet-repository' +build
      - name: Publish site to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: build
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
